import JSZip from "jszip";
import { PdfPageData } from "./pdf-engine";

export type RenderMode = "html" | "canvas" | "hybrid";

export class Exporter {
  static generateHtml(pages: PdfPageData[], mode: RenderMode): string {
    const pagesHtml = pages
      .map((page) => {
        const pageStyle = `
        position: relative;
        width: ${page.width}px;
        height: ${page.height}px;
        margin: 0 auto 20px auto;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        background-color: white;
        overflow: hidden;
      `;

        let backgroundHtml = "";
        if (mode === "canvas" || mode === "hybrid") {
          backgroundHtml = `<img src="${page.canvasDataUrl}" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" />`;
        }

        let textHtml = "";
        if (mode === "html" || mode === "hybrid") {
          textHtml = page.textItems
            .map((item) => {
              const style = `
            position: absolute;
            left: ${item.x}px;
            top: ${item.y}px;
            font-size: ${item.fontSize}px;
            font-family: ${item.fontFamily}, sans-serif;
            font-weight: ${item.fontWeight};
            font-style: ${item.fontStyle};
            text-decoration: ${item.textDecoration};
            ${item.letterSpacing > 0 ? `letter-spacing: ${item.letterSpacing}px;` : ''}
            transform-origin: left bottom;
            white-space: pre;
            ${mode === "hybrid" ? "color: transparent; user-select: text;" : "color: black;"}
          `;
              return `<div style="${style}">${escapeHtml(item.str)}</div>`;
            })
            .join("\\n");
        }

        return `<div class="pdf-page" style="${pageStyle}">
        ${backgroundHtml}
        ${textHtml}
      </div>`;
      })
      .join("\\n");

    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PDF2HTML Export</title>
  <style>
    body {
      background-color: #f3f4f6;
      padding: 20px;
      font-family: sans-serif;
    }
  </style>
</head>
<body>
  ${pagesHtml}
</body>
</html>
    `.trim();
  }

  static async generateZip(htmlContent: string): Promise<Blob> {
    const zip = new JSZip();
    zip.file("output.html", htmlContent);
    zip.file("README.txt", "Generated by PDF2HTML Studio.");
    return await zip.generateAsync({ type: "blob" });
  }
}

function escapeHtml(unsafe: string): string {
  return unsafe
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
